[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "arana"
authors = [{name = "Arana", email = "jjeffcaii@yandex.com"}]
dynamic = ["version", "description"]
